name: CML Model Testing AMP
description: |
  A demonstration of how CML Models can be deployed and used with applications

author: Cloudera Inc.
specification_version: 1.0
prototype_version: 1.0
date: "2023-07-21"

runtimes:
  - editor: Workbench
    kernel: Python 3.9
    edition: Nvidia GPU

tasks:
  - type: run_session
    name: Install Dependencies
    script: session-install-deps/install_setup_tools.py
    short_summary: Install Dependencies
    kernel: python3
    cpu: 2
    memory: 16
  - type: run_session
    name: Install Dependencies
    script: session-install-deps/install_dependencies.py
    short_summary: Install Dependencies
    kernel: python3
    cpu: 2
    memory: 16
  - type: create_model
    name: Chat_model
    entity_label: llm
    description: Chat Model 
    short_summary: Deploying a sample model that runs CML Model
    default_resources:
    cpu: 4
    memory: 32
    gpu: 1
  - type: build_model
    entity_label: llm
    comment: Some comment about the model
    examples:
      - request:
          prompt: Name 5 cities in United States
    target_file_path: gradio-app/app.py
    target_function_name: api_wrapper
    kernel: python3
  - type: deploy_model
    entity_label: llm
    cpu: 4
    memory: 32
    gpu: 1

  # - type: start_application
  #   name: CML LLM Test App
  #   subdomain: cmlllm
  #   script: gradio-app/app.py
  #   short_summary: Start CML LLM Chatbot application
  #   long_summary: This application requires an available GPU to run the LLM model. Startup may be delayed if autoscaling is being performed or fail if GPU cannot be scheduled on this workspace. Please contact your administrator for GPU scheduling.
  #   cpu: 4
  #   memory: 32
  #   gpu: 1
  #   environment_variables:
  #     TASK_TYPE: START_APPLICATION
